import { createContext, useContext, useState } from 'react';

const translations = {
  es: {
    header: {
      aiActive: 'IA Activa',
      login: 'Iniciar sesión',
      profile: 'Mi perfil',
      logout: 'Cerrar sesión',
    },
    hero: {
      badge: 'Inteligencia de Contenido con IA',
      title1: 'Deja de publicar',
      title2: 'a ciegas.',
      desc1: 'HookFit analiza tus vídeos de fitness con IA y te dice',
      descHighlight: 'en qué segundo exacto pierdes audiencia',
      desc2: ', cómo mejorar tu hook y qué editar para retener.',
      desc3pre: 'Pensado para',
      creators: 'creadores fitness',
      and: 'y',
      coaches: 'coaches online',
      desc3post: 'que quieren convertir visualizaciones en crecimiento real.',
      features: [
        { label: 'Optimización del Hook', desc: 'Evalúa tus primeros 3 segundos vs. contenido viral' },
        { label: 'Análisis de Retención', desc: 'Detecta el segundo exacto donde pierdes audiencia' },
        { label: 'Diagnóstico y Edición', desc: 'Consejos de recorte, ritmo visual y estructura' },
        { label: 'Espía de Mercado', desc: 'Analiza vídeos virales de las últimas 24h' },
        { label: 'Tipo Estratégico', desc: 'Alcance, Autoridad o Conversión' },
        { label: 'IA Avanzada', desc: 'Análisis con inteligencia artificial de última gen.' },
      ],
    },
    sidebar: {
      home: 'Inicio',
      spy: 'Espía Intel',
      profile: 'Mi perfil',
      proActive: 'PRO Activo',
      planFree: 'Plan Free',
    },
    pricing: {
      badge: 'Planes y Precios',
      title: 'Elige tu plan para',
      titleHighlight: 'crecer',
      subtitle: 'Desbloquea el análisis completo de tus vídeos y convierte tus visualizaciones en crecimiento real.',
      proActiveBadge: 'Plan Pro activo — Tienes acceso completo',
      plans: [
        {
          name: 'Free',
          period: 'para siempre',
          description: 'Descubre lo que HookFit puede hacer por tu contenido.',
          features: [
            'Ver qué analiza HookFit',
            'Explorar la demo interactiva',
            'Ver ejemplo de análisis completo',
            'Acceso a la landing y recursos',
          ],
          locked: [
            'Analizar tus propios vídeos',
            'Espía de inteligencia de mercado',
            'Análisis ilimitados',
            'Soporte prioritario',
          ],
          cta: 'Plan Actual',
        },
        {
          name: 'Pro',
          badge: 'Popular',
          description: 'Todo lo que necesitas para crecer como creador fitness.',
          features: [
            'Análisis ilimitados de vídeos',
            'Análisis de Retención con IA',
            'Optimización de Hook (3 seg.)',
            'Diagnóstico + soluciones concretas',
            'Espía Intel — vídeos virales 24h',
            'Métricas de engagement avanzadas',
            'Consejos de edición personalizados',
            'Soporte prioritario',
          ],
          cta: 'Desbloquear Pro',
        },
        {
          name: 'Agency',
          description: 'Para agencias y coaches que gestionan múltiples creadores.',
          features: [
            'Todo en Pro',
            'Hasta 10 perfiles de creadores',
            'Análisis comparativo entre perfiles',
            'Reportes exportables en PDF',
            'Dashboard de equipo',
            'API access',
            'Soporte dedicado 24/7',
          ],
          cta: 'Contactar',
        },
      ],
    },
    auth: {
      back: 'Volver al inicio',
      loginTitle: 'Inicia sesión',
      registerTitle: 'Crea tu cuenta',
      loginDesc: 'Accede a tu cuenta para analizar tus vídeos.',
      registerDesc: 'Regístrate gratis y empieza a analizar tu contenido.',
      googleLogin: 'Iniciar sesión con Google',
      googleRegister: 'Registrarse con Google',
      orEmail: 'o con correo',
      nameLabel: 'Nombre',
      namePlaceholder: 'Tu nombre',
      emailLabel: 'Correo electrónico',
      emailPlaceholder: 'tu@correo.com',
      passwordLabel: 'Contraseña',
      forgotPassword: '¿Olvidaste tu contraseña?',
      loginBtn: 'Iniciar sesión',
      registerBtn: 'Crear cuenta',
      noAccount: '¿No tienes cuenta?',
      hasAccount: '¿Ya tienes cuenta?',
      registerLink: 'Regístrate',
      loginLink: 'Inicia sesión',
    },
    steps: {
      title1: 'De la idea a lo viral',
      title2: 'en 3 pasos.',
      subtitle: 'Un sistema probado para convertir visualizaciones en crecimiento real.',
      items: [
        { title: 'Sube tu vídeo', desc: 'Sube cualquier clip de fitness o coaching. Nuestra IA lo analiza en segundos.' },
        { title: 'Diagnóstico con IA', desc: 'Detectamos el punto de fuga, analizamos tu hook y evaluamos la retención completa.' },
        { title: 'Aplica y crece', desc: 'Recibe consejos de edición concretos, optimiza tu estructura y replica el éxito.' },
      ],
    },
    cta: {
      title1: 'Únete a la nueva era',
      title2: 'de creadores.',
      subtitle: 'No dejes que tu próxima idea viral pase de largo por falta de estructura.',
      btnPro: 'Analizar mi vídeo',
      btnFree: 'Empezar ahora',
    },
    error: {
      title: 'Error de Análisis',
    },
    spy: {
      lockedTitle: 'Espía de Inteligencia',
      lockedDesc: 'Analiza vídeos virales de otros creadores en las últimas 24h. Descubre qué estructuras y hooks están funcionando ahora mismo.',
      lockedBtn: 'Desbloquear con Pro',
      headerTitle: 'Espía',
      headerHighlight: 'Intel',
      headerSub: 'Inteligencia de mercado en tiempo real',
      liveBadge: 'Live — Últimas 24h',
      insights: [
        { title: 'Tendencia del momento', value: 'Formato POV + educación', desc: 'Los vídeos "POV" educativos tienen un 340% más de shares esta semana.' },
        { title: 'Duración óptima', value: '15-22 segundos', desc: 'El punto dulce de retención en fitness content esta semana.' },
        { title: 'Hook dominante', value: 'Text overlay + acción', desc: '68% de los vídeos virales usan texto en los primeros 0.5s.' },
      ],
      viralTitle: 'Vídeos Virales Detectados',
      viralCount: 'esta semana',
      hookLabel: 'Hook Analysis',
      structureLabel: 'Estructura',
      retentionLabel: 'Retención',
      creatorsTitle: 'Pensado para Creadores y Coaches',
      creatorsDesc: 'Convierte tus visualizaciones en leads reales. Usa los datos de inteligencia para replicar las estructuras que funcionan y aplicarlas a tu propio contenido de fitness.',
      creatorsBtn: 'Analizar mi vídeo',
    },
    footer: {
      tagline1: 'Motor de crecimiento estratégico con IA para creadores fitness.',
      tagline2: 'No solo puntuaciones —',
      tagline3: 'sistemas',
      builtWith: 'Hecho con',
    },
    profile: {
      defaultName: 'Usuario',
      memberSince: 'Miembro desde',
      totalAnalyses: 'Análisis totales',
      avgHookScore: 'Hook promedio',
      bestScore: 'Mejor puntuación',
      historyTitle: 'Historial de análisis',
      historyDesc: 'Todos tus vídeos analizados',
      loading: 'Cargando historial...',
      emptyTitle: 'Sin análisis aún',
      emptyDesc: 'Cuando analices tu primer vídeo, aparecerá aquí.',
    },
    report: {
      newAnalysis: 'Nuevo Análisis',
      analysisComplete: 'Análisis Completado',
      overall: 'GENERAL',
      topPriority: 'Prioridad Principal',
      hookAnalysis: 'Análisis del Hook',
      messageClarity: 'Claridad del Mensaje',
      coreMessage: 'Mensaje Principal',
      improvedHook: 'Hook Mejorado',
      restructureTip: 'Consejo de Reestructura',
      retentionTimeline: 'Línea Temporal de Retención',
      noRetentionRisks: 'No se detectaron riesgos de retención significativos. ¡Buen trabajo!',
      energyDelivery: 'Energía y Entrega',
      speechTempo: 'Ritmo del Habla',
      vocalVariation: 'Variación Vocal',
      authority: 'Autoridad',
      deliveryTip: 'Consejo de Entrega',
      strategicClass: 'Clasificación Estratégica',
      optimizationTips: 'Consejos de Optimización',
      confidence: 'Confianza',
      readyToImprove: '¿Listo para mejorar?',
      readyDesc: 'Aplica el feedback, vuelve a grabar y analiza de nuevo para seguir tu crecimiento.',
      analyzeAnother: 'Analizar Otro Vídeo',
      suggestion: 'Sugerencia',
      strategyReach: 'Enfoque en atención — diseñado para maximizar vistas y compartidos',
      strategyAuthority: 'Enfoque en credibilidad — construye confianza y percepción de expertise',
      strategyConversion: 'Enfoque en oferta — impulsa clics, registros o compras',
      strategyCommunity: 'Enfoque en conexión — cercanía y construcción de comunidad',
    },
    upload: {
      sectionLabel: 'Subir y Analizar',
      tabUpload: 'Subir Vídeo',
      tabUrl: 'Pegar URL',
      readyToAnalyze: 'Listo para analizar',
      remove: 'Eliminar',
      dropHere: '¡Suéltalo aquí!',
      dragDrop: 'Arrastra y suelta tu vídeo',
      fileTypes: 'MP4, MOV o WebM • Hasta 100MB',
      orBrowse: 'o haz clic para buscar',
      urlLabel: 'URL del Vídeo',
      analyzeBtn: 'Analizar Vídeo',
      or: 'o',
      demoBtn: 'Probar Análisis Demo',
      demoNote: '— sin necesidad de subir',
    },
    loading: {
      title: 'Analizando tu',
      titleHighlight: 'contenido',
      subtitle: 'La IA de HookFit está analizando tu vídeo en 6 dimensiones...',
      progress: 'Progreso',
      steps: [
        { label: 'Procesando vídeo', detail: 'Extrayendo fotogramas y metadatos' },
        { label: 'Extrayendo audio', detail: 'Convirtiendo a datos de onda' },
        { label: 'Transcribiendo voz', detail: 'Whisper AI speech-to-text' },
        { label: 'Analizando hook', detail: 'Evaluación de los primeros 3-5 segundos' },
        { label: 'Detectando riesgos de retención', detail: 'Mapeando riesgos en la línea temporal' },
        { label: 'Generando reporte estratégico', detail: 'Creando insights accionables' },
      ],
      done: 'Hecho',
    },
  },
  en: {
    header: {
      aiActive: 'AI Active',
      login: 'Sign in',
      profile: 'My profile',
      logout: 'Sign out',
    },
    hero: {
      badge: 'AI-Powered Content Intelligence',
      title1: 'Stop posting',
      title2: 'blindly.',
      desc1: 'HookFit analyzes your fitness videos with AI and tells you',
      descHighlight: 'the exact second you lose your audience',
      desc2: ', how to improve your hook, and what to edit for retention.',
      desc3pre: 'Built for',
      creators: 'fitness creators',
      and: 'and',
      coaches: 'online coaches',
      desc3post: 'who want to turn views into real growth.',
      features: [
        { label: 'Hook Optimization', desc: 'Evaluate your first 3 seconds vs. viral content' },
        { label: 'Retention Analysis', desc: 'Detect the exact second where you lose your audience' },
        { label: 'Editing Diagnosis', desc: 'Trim tips, visual pacing, and structure advice' },
        { label: 'Market Spy', desc: 'Analyze viral videos from the last 24h' },
        { label: 'Strategic Type', desc: 'Reach, Authority, or Conversion' },
        { label: 'Advanced AI', desc: 'Analysis with cutting-edge artificial intelligence' },
      ],
    },
    sidebar: {
      home: 'Home',
      spy: 'Spy Intel',
      profile: 'My profile',
      proActive: 'PRO Active',
      planFree: 'Free Plan',
    },
    pricing: {
      badge: 'Plans & Pricing',
      title: 'Choose your plan to',
      titleHighlight: 'grow',
      subtitle: 'Unlock the full analysis of your videos and turn your views into real growth.',
      proActiveBadge: 'Pro Plan active — You have full access',
      plans: [
        {
          name: 'Free',
          period: 'forever',
          description: 'Discover what HookFit can do for your content.',
          features: [
            'See what HookFit analyzes',
            'Explore the interactive demo',
            'View a full analysis example',
            'Access to the landing and resources',
          ],
          locked: [
            'Analyze your own videos',
            'Market intelligence spy',
            'Unlimited analyses',
            'Priority support',
          ],
          cta: 'Current Plan',
        },
        {
          name: 'Pro',
          badge: 'Popular',
          description: 'Everything you need to grow as a fitness creator.',
          features: [
            'Unlimited video analyses',
            'AI Retention Analysis',
            'Hook Optimization (3 sec.)',
            'Diagnosis + concrete solutions',
            'Spy Intel — 24h viral videos',
            'Advanced engagement metrics',
            'Personalized editing advice',
            'Priority support',
          ],
          cta: 'Unlock Pro',
        },
        {
          name: 'Agency',
          description: 'For agencies and coaches managing multiple creators.',
          features: [
            'Everything in Pro',
            'Up to 10 creator profiles',
            'Comparative analysis across profiles',
            'Exportable PDF reports',
            'Team dashboard',
            'API access',
            'Dedicated 24/7 support',
          ],
          cta: 'Contact',
        },
      ],
    },
    auth: {
      back: 'Back to home',
      loginTitle: 'Sign in',
      registerTitle: 'Create your account',
      loginDesc: 'Access your account to analyze your videos.',
      registerDesc: 'Sign up for free and start analyzing your content.',
      googleLogin: 'Sign in with Google',
      googleRegister: 'Sign up with Google',
      orEmail: 'or with email',
      nameLabel: 'Name',
      namePlaceholder: 'Your name',
      emailLabel: 'Email address',
      emailPlaceholder: 'you@email.com',
      passwordLabel: 'Password',
      forgotPassword: 'Forgot your password?',
      loginBtn: 'Sign in',
      registerBtn: 'Create account',
      noAccount: "Don't have an account?",
      hasAccount: 'Already have an account?',
      registerLink: 'Sign up',
      loginLink: 'Sign in',
    },
    steps: {
      title1: 'From idea to viral',
      title2: 'in 3 steps.',
      subtitle: 'A proven system to turn views into real growth.',
      items: [
        { title: 'Upload your video', desc: 'Upload any fitness or coaching clip. Our AI analyzes it in seconds.' },
        { title: 'AI Diagnosis', desc: 'We detect the drop-off point, analyze your hook, and evaluate full retention.' },
        { title: 'Apply and grow', desc: 'Get concrete editing tips, optimize your structure, and replicate success.' },
      ],
    },
    cta: {
      title1: 'Join the new era',
      title2: 'of creators.',
      subtitle: "Don't let your next viral idea slip away due to lack of structure.",
      btnPro: 'Analyze my video',
      btnFree: 'Get started',
    },
    error: {
      title: 'Analysis Error',
    },
    spy: {
      lockedTitle: 'Intelligence Spy',
      lockedDesc: "Analyze other creators' viral videos from the last 24h. Discover which structures and hooks are working right now.",
      lockedBtn: 'Unlock with Pro',
      headerTitle: 'Spy',
      headerHighlight: 'Intel',
      headerSub: 'Real-time market intelligence',
      liveBadge: 'Live — Last 24h',
      insights: [
        { title: 'Trending now', value: 'POV + education format', desc: 'Educational "POV" videos have 340% more shares this week.' },
        { title: 'Optimal duration', value: '15-22 seconds', desc: 'The retention sweet spot for fitness content this week.' },
        { title: 'Dominant hook', value: 'Text overlay + action', desc: '68% of viral videos use text in the first 0.5s.' },
      ],
      viralTitle: 'Viral Videos Detected',
      viralCount: 'this week',
      hookLabel: 'Hook Analysis',
      structureLabel: 'Structure',
      retentionLabel: 'Retention',
      creatorsTitle: 'Built for Creators and Coaches',
      creatorsDesc: 'Turn your views into real leads. Use intelligence data to replicate the structures that work and apply them to your own fitness content.',
      creatorsBtn: 'Analyze my video',
    },
    footer: {
      tagline1: 'AI-powered strategic growth for fitness creators.',
      tagline2: 'Not just scores —',
      tagline3: 'systems',
      builtWith: 'Built with',
    },
    profile: {
      defaultName: 'User',
      memberSince: 'Member since',
      totalAnalyses: 'Total analyses',
      avgHookScore: 'Avg hook score',
      bestScore: 'Best score',
      historyTitle: 'Analysis history',
      historyDesc: 'All your analyzed videos',
      loading: 'Loading history...',
      emptyTitle: 'No analyses yet',
      emptyDesc: 'When you analyze your first video, it will appear here.',
    },
    report: {
      newAnalysis: 'New Analysis',
      analysisComplete: 'Analysis Complete',
      overall: 'OVERALL',
      topPriority: 'Top Priority',
      hookAnalysis: 'Hook Analysis',
      messageClarity: 'Message Clarity',
      coreMessage: 'Core Message',
      improvedHook: 'Improved Hook',
      restructureTip: 'Restructure Tip',
      retentionTimeline: 'Retention Risk Timeline',
      noRetentionRisks: 'No significant retention risks detected. Nice work!',
      energyDelivery: 'Energy & Delivery',
      speechTempo: 'Speech Tempo',
      vocalVariation: 'Vocal Variation',
      authority: 'Authority',
      deliveryTip: 'Delivery Tip',
      strategicClass: 'Strategic Classification',
      optimizationTips: 'Optimization Tips',
      confidence: 'Confidence',
      readyToImprove: 'Ready to improve?',
      readyDesc: 'Apply the feedback, re-shoot, and analyze again to track your growth.',
      analyzeAnother: 'Analyze Another Video',
      suggestion: 'Suggestion',
      strategyReach: 'Attention-focused — designed to maximize views and shares',
      strategyAuthority: 'Credibility-focused — builds trust and expertise perception',
      strategyConversion: 'Offer-focused — drives clicks, sign-ups, or purchases',
      strategyCommunity: 'Bonding-focused — relatability and connection building',
    },
    upload: {
      sectionLabel: 'Upload & Analyze',
      tabUpload: 'Upload Video',
      tabUrl: 'Paste URL',
      readyToAnalyze: 'Ready to analyze',
      remove: 'Remove',
      dropHere: 'Drop it right here!',
      dragDrop: 'Drag & drop your video',
      fileTypes: 'MP4, MOV, or WebM • Up to 100MB',
      orBrowse: 'or click to browse',
      urlLabel: 'Video URL',
      analyzeBtn: 'Analyze Video',
      or: 'or',
      demoBtn: 'Try Demo Analysis',
      demoNote: '— no upload needed',
    },
    loading: {
      title: 'Analyzing your',
      titleHighlight: 'content',
      subtitle: 'HookFit AI is breaking down your video across 6 dimensions...',
      progress: 'Progress',
      steps: [
        { label: 'Processing video', detail: 'Extracting frames and metadata' },
        { label: 'Extracting audio', detail: 'Converting to waveform data' },
        { label: 'Transcribing speech', detail: 'Whisper AI speech-to-text' },
        { label: 'Analyzing hook', detail: 'First 3-5 seconds evaluation' },
        { label: 'Detecting retention risks', detail: 'Timeline risk mapping' },
        { label: 'Building strategic report', detail: 'Generating actionable insights' },
      ],
      done: 'Done',
    },
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('es');

  const toggleLang = () => setLang((prev) => (prev === 'es' ? 'en' : 'es'));

  const t = translations[lang];

  return (
    <LanguageContext.Provider value={{ lang, toggleLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
}
